### ISSUE TITLE
Endstop Alway triggered with same configuration

### ISSUE THREAD

**Issue by Verbo1979** [lele344/Predator#1]
Come segnalato da lele e già constatato in precedenza ho invertito i cavi esterni degli endstop, ma il segnale rimane sempre attivo(o disattivo invertento da false a true sul firmware), domani proverò a controllare il sengale con il potenziometro

**Comment by lele344** [comment]
Ciao Verbo, tieni presente che se stai usando la versione che ho caricato io, devi collegare gli endstop non a X- Y- Z- ma a E0DET (X), E1DET (y) e PWRDET (z).
![image](https://user-images.githubusercontent.com/7257088/74985754-6a819380-5438-11ea-8dd7-0c8d871c16a8.png)

Questo perchè ho voluto usare non le porte X, Y, Z MIN ma le XYZ MAX.

Devo ancora sistemare il sensore di filamento smart della BTT, ma il resto funziona e alla grande.
Se hai bisogno non esitare a contattarmi.

**Comment by Verbo1979** [comment]
Già fatto, era scritto nella descrizione e nelle cartesiane cambio spesso
le porte per comodità...non capisco, anche le letture da potenziometro sono
corrette

Il gio 20 feb 2020, 23:26 lele344 <notifications@github.com> ha scritto:

**Comment by lele344** [comment]
hai provato a fare il disabled dei motori e spostare a mano uno alla volta i carrelli e verificare con M119 lo stato degli endstop?
Te lo dico perchè potrebbe essere che hai definito l'altezza della delta troppo bassa come valore, e andando in home, non arrivi agli endstop.
Prova manualmente e verifica uno alla volta se i sensori ti vanno in triggered.
Se cosi fosse, basta che ricarichi il firmware impostando un:
  #define DELTA_HEIGHT ad un valore elevato tipo 500 al posto di 438.08  (quello che io) e rifai il delta calibration, quindi inserisci i valori ottenuti nel firmware e ricarichi.
I led degli endstop, si accendono?

**Comment by Verbo1979** [comment]
Già fatto, sono sempre accesi e in stato triggered, mi rimane solo da
provare con altri endstop o rifare da 0 la cablatura, domani provo e
aggiorno

Il gio 20 feb 2020, 23:47 lele344 <notifications@github.com> ha scritto:

**Comment by lele344** [comment]
stai usando gli endstop originali di Anycubic? stai usando pullups o pulldowns sugli endstop?
ricontrolla il cablaggio, non so se mi ero spiegato bene nella descrizione (devo ancora sistemarla ma il tempo è tiranno) ma devi invertire il "+" e il "S" se usi il cavo originale della anycubic (poichè nella trigorilla invertivano i pin).
Scusa ma ora ho la stampante tutta chiusa con Palette sopra e sta lavorando ma se non ricordo male, Anycubic predator usa come endstop i Geeetech 3d printer opto optical:
![image](https://user-images.githubusercontent.com/7257088/74988747-fb5b6d80-543e-11ea-8a33-6be039d6e229.png)

l'ordine (ma verificalo) dovrebbe essere  V S G.
La scheda BTT SKR 1.4 (e turbo) usa la disposizione V G S.
Quindi devi invertire (se parti da un filo nuovo) la G e la S.

Ripeto: vado a memoria, quindi prendi tutto quello che ti dico ora con le pinze.

**Comment by Verbo1979** [comment]
Confermo, ho provato un endstop meccanico e funziona correttamente con i
suoi cavi, domani smonto con calma i geeetech e  verifico la cablatura, di
sicuro è lì il problema! Grazie ancora per la disponibilità!

Il ven 21 feb 2020, 00:16 lele344 <notifications@github.com> ha scritto:

**Comment by lele344** [comment]
Ciao Verbo1979, hai risolto? posso chiudere l'issue?

**Comment by Verbo1979** [comment]
Finito ora, ho rifatto i cavi e funziona tutto perfettamente! Grazie ancora
per l'aiuto!

Il sab 22 feb 2020, 18:45 lele344 <notifications@github.com> ha scritto:

**Comment by lele344** [comment]
felice di sapere che hai risolto! buone stampe!
